import fs from 'fs';
import path from 'path';

const catalogCode = `import { ArticleItem, ColorTheme, CatalogConfig } from '../types';

export const THEMES: Record<string, ColorTheme> = {
  clair: {
    id: 'clair',
    name: 'Thème Clair',
    bgColor: '#FFFFFF',
    cardBg: '#FAFAF8',
    textColor: '#1E1915',
    mutedTextColor: '#635950',
    accentColor: '#8C6239',
    borderColor: '#E2DBD0',
    headerAccent: '#2C221B',
    badgeBg: '#F3EDE4',
    badgeText: '#4A331E',
  },
  fonce: {
    id: 'fonce',
    name: 'Thème Foncé',
    bgColor: '#171412',
    cardBg: '#211C18',
    textColor: '#F5F2ED',
    mutedTextColor: '#A89E94',
    accentColor: '#D4A373',
    borderColor: '#383028',
    headerAccent: '#FAF6F0',
    badgeBg: '#2E2620',
    badgeText: '#F0DEC8',
  },
  sepia: {
    id: 'clair',
    name: 'Thème Clair',
    bgColor: '#FFFFFF',
    cardBg: '#FAFAF8',
    textColor: '#1E1915',
    mutedTextColor: '#635950',
    accentColor: '#8C6239',
    borderColor: '#E2DBD0',
    headerAccent: '#2C221B',
    badgeBg: '#F3EDE4',
    badgeText: '#4A331E',
  },
};

export const COLOR_THEMES = THEMES;

export const DEFAULT_CONFIG: CatalogConfig = {
  mainTitle: 'CASA MADRE',
  subtitle: 'Dépôt Antiquités',
  collection: '',
  activeFolder: 'Antiquités',
  folders: ['Antiquités', 'Halloween'],
  contactInfo: '',
  dateStr: 'SEPTEMBRE 2026',
  catalogRef: 'INV-2025/01',
  layoutMode: '2-per-page',
  themeId: 'clair',
  showPrices: false,
  showDimensions: false,
  showReference: false,
  headerEveryPage: true,
  notesFooter: 'Expertise & authenticité garanties • Visites sur rendez-vous à l\\\'atelier',
  cleanScanEffect: true,
  uiDarkMode: false,
};

export const INITIAL_ARTICLES: ArticleItem[] = [
  // Page 1
  {
    id: 'art-antiq-01',
    ref: 'INV-2025/01-01',
    name: 'Cassette VHS Disney « Le Retour de Jafar » avec boîtier',
    imageUrl: '/vhs_jafar.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Vidéos & Cassettes VHS',
    material: 'Boîtier plastique blanc d\\\'origine, jaquette illustrée, bande magnétique VHS',
    periodOrStyle: 'Années 1990 (1994, Walt Disney Vidéo)',
    condition: 'Bon état général d\\\'usage, boîtier complet avec jaquette couleur',
    dimensions: 'H : 19 cm × L : 10,5 cm × P : 3 cm',
    quantity: '51',
    price: '',
    notes: 'Premier film d\\\'animation Disney sorti directement en vidéo, suite officielle d\\\'Aladdin.',
  },
  {
    id: 'art-antiq-02',
    ref: 'INV-2025/01-02',
    name: 'Disque Vinyle 33 Tours Demis Roussos (Label Philips)',
    imageUrl: '/vinyle_demis_roussos.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Musique & Vinyles Vintage',
    material: 'Disque vinyle microsillon 33 RPM, macaron Philips stéréo, pochette cartonnée',
    periodOrStyle: 'Années 1970 (1973, Pressage Philips France)',
    condition: 'Bon état vintage, sillon lisible, pochette conservée',
    dimensions: 'Diamètre : 30 cm (Format LP 12")',
    quantity: '111',
    price: '',
    notes: 'Album culte « Forever and Ever » de Demis Roussos, pressage stéréo référence 6325 021.',
  },

  // Page 2
  {
    id: 'art-antiq-03',
    ref: 'INV-2025/01-03',
    name: 'Lot de Disques Vinyles 45 Tours Vintage (Pochette Rouge)',
    imageUrl: '/antiquites/vinyl_45t.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Musique & Vinyles Vintage',
    material: 'Disques vinyles 45 RPM, pochettes papier et cartonné d\\\'époque',
    periodOrStyle: 'Années 1960 - 1980',
    condition: 'Ensemble de disques authentiques de collection',
    dimensions: 'Diamètre : 17,5 cm (Format 7")',
    quantity: '168',
    price: '',
    notes: 'Important lot de 45 tours vintage variés avec macarons originaux.',
  },
  {
    id: 'art-antiq-04',
    ref: 'INV-2025/01-04',
    name: 'Lecteur DVD & Platine de Salon Argentée',
    imageUrl: '/antiquites/dvd_player_silver.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Hi-Fi & Vidéo Vintage',
    material: 'Châssis métallique finition argentée brossée, afficheur digital LED',
    periodOrStyle: 'Années 2000',
    condition: 'Bon état cosmétique et fonctionnel',
    dimensions: 'L : 43 cm × P : 28 cm × H : 6 cm',
    quantity: '1',
    price: '',
    notes: 'Platine de salon pour lecture DVD Vidéo et CD Audio.',
  },

  // Page 3
  {
    id: 'art-antiq-05',
    ref: 'INV-2025/01-05',
    name: 'Décodeur / Récepteur Vidéo Vintage Noir & Adaptateur',
    imageUrl: '/antiquites/decoder_receiver.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Appareils Électroniques & Rétro',
    material: 'Boîtier plastique noir, transformateur d\\\'alimentation secteur externe',
    periodOrStyle: 'Années 1990 - 2000',
    condition: 'Complet avec son adaptateur d\\\'alimentation d\\\'origine',
    dimensions: 'L : 26 cm × P : 18 cm × H : 5 cm',
    quantity: '1',
    price: '',
    notes: 'Récepteur vidéo compact avec voyants de façade.',
  },
  {
    id: 'art-antiq-06',
    ref: 'INV-2025/01-06',
    name: 'Projecteur Cinéma Super 8 à Bobine Vintage',
    imageUrl: '/antiquites/projector_super8.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Cinéma & Matériel de Projection',
    material: 'Fonte d\\\'aluminium et carter acier, bras mécanique porte-bobine',
    periodOrStyle: 'Années 1970',
    condition: 'Bel état mécanique et optique avec bobine d\\\'origine',
    dimensions: 'L : 32 cm × P : 20 cm × H : 28 cm',
    quantity: '1',
    price: '',
    notes: 'Projecteur de film cinéma argentique Super 8 pour séances familiales rétro.',
  },

  // Page 4
  {
    id: 'art-antiq-07',
    ref: 'INV-2025/01-07',
    name: 'Collection de Bouteilles Vintage en Verre Sérigraphié',
    imageUrl: '/antiquites/bottles_collection.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Objets de Collection & Verrerie',
    material: 'Verre teinté épais (vert, ambre, transparent), sérigraphies d\\\'époque',
    periodOrStyle: 'Années 1970 - 1980',
    condition: 'Bouteilles saines sans ébréchure, marquages nets (Fanta, 7Up, Crush)',
    dimensions: 'Hauteur moyenne : 24 à 30 cm',
    quantity: '1',
    price: '',
    notes: 'Ensemble de bouteilles collector de boissons gazeuses rétro.',
  },
  {
    id: 'art-antiq-08',
    ref: 'INV-2025/01-08',
    name: 'Machine à Écrire Mécanique Vintage Beige & Noire',
    imageUrl: '/antiquites/typewriter_vintage.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Machines de Bureau Anciennes',
    material: 'Châssis tôle emboutie émaillée, touches en bakélite et plastique',
    periodOrStyle: 'Années 1960 - 1970',
    condition: 'Mécanique fluide, rouleau et chariot en bon état d\\\'usage',
    dimensions: 'L : 32 cm × P : 34 cm × H : 12 cm',
    quantity: '1',
    price: '',
    notes: 'Machine à écrire portative avec clavier azerty complet.',
  },

  // Page 5
  {
    id: 'art-antiq-09',
    ref: 'INV-2025/01-09',
    name: 'Ensemble de clubs de golf avec sac',
    imageUrl: '/antiquites/golf_bag_clubs.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Sport & Loisirs de Collection',
    material: 'Métal, bois et textile',
    periodOrStyle: 'Milieu du XXe siècle',
    condition: 'Très bel état vintage avec sac de transport et clubs assortis',
    dimensions: 'H sac : 90 cm (Clubs : 95 à 110 cm)',
    quantity: '1',
    price: '',
    notes: 'Série complète de fers et bois traditionnels avec sac en toile et cuir.',
  },
  {
    id: 'art-antiq-10',
    ref: 'INV-2025/01-10',
    name: 'Trépied photo',
    imageUrl: '/antiquites/tripod_photo.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Photographie & Optique',
    material: 'Aluminium et plastique',
    periodOrStyle: 'Contemporain',
    condition: 'Branches télescopiques réglables et platine orientable',
    dimensions: 'Hauteur réglable de 45 à 140 cm',
    quantity: '1',
    price: '',
    notes: 'Trépied photo stable pour appareil argentique ou numérique.',
  },

  // Page 6
  {
    id: 'art-antiq-11',
    ref: 'INV-2025/01-11',
    name: 'Raquette Maxima de Tennis de Table / Badminton Vintage',
    imageUrl: '/antiquites/racket_maxima.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Sport & Jeux Vintage',
    material: 'Bois multiplis, manche profilé, sérigraphie Maxima bleue',
    periodOrStyle: 'Années 1970 - 1980',
    condition: 'Bon état vintage avec marquage Maxima intact',
    dimensions: 'L : 38 cm × L tamis : 19 cm',
    quantity: '1',
    price: '',
    notes: 'Raquette de sport vintage pour décoration ou jeu récréatif.',
  },
  {
    id: 'art-antiq-12',
    ref: 'INV-2025/01-12',
    name: 'Manette PlayStation Transparente Bleue',
    imageUrl: '/antiquites/playstation_controller_blue.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Jeux Vidéo & Rétrogaming',
    material: 'Plastique translucide bleu, boutons analogiques et câble officiel',
    periodOrStyle: 'Années 1990 - 2000 (Sony PlayStation)',
    condition: 'Câble intact, boîtier transparent laissant apparaître les circuits',
    dimensions: 'L : 15 cm × P : 10 cm',
    quantity: '1',
    price: '',
    notes: 'Manette DualShock officielle Sony en édition Crystal Blue.',
  },

  // Page 7
  {
    id: 'art-antiq-13',
    ref: 'INV-2025/01-13',
    name: 'Manette Joystick Arcade Rétro à Bouton Rouge',
    imageUrl: '/antiquites/arcade_joystick.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Jeux Vidéo & Rétrogaming',
    material: 'Boîtier plastique jaune et violet, tige métallique et boule rouge',
    periodOrStyle: 'Années 1980 - 1990',
    condition: 'Boutons réactifs et stick arcade solide',
    dimensions: 'L : 18 cm × P : 14 cm × H : 16 cm',
    quantity: '1',
    price: '',
    notes: 'Contrôleur arcade authentique pour jeux de combat et bornes rétro.',
  },
  {
    id: 'art-antiq-14',
    ref: 'INV-2025/01-14',
    name: 'Caméra & Projecteur Cinéma Vintage dans sa Boîte en Bois',
    imageUrl: '/antiquites/cinema_camera_box.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Cinéma & Optique Ancienne',
    material: 'Coffret bois verni avec fermoirs métalliques, appareil optique vintage',
    periodOrStyle: 'Milieu du XXe siècle',
    condition: 'Coffret protecteur complet avec accessoires d\\\'origine',
    dimensions: 'Coffret : 36 cm × 24 cm × 18 cm',
    quantity: '1',
    price: '',
    notes: 'Ensemble de projection cinéma portable dans sa mallette d\\\'atelier.',
  },

  // Page 8
  {
    id: 'art-antiq-15',
    ref: 'INV-2025/01-15',
    name: 'Jeu Électronique Portable Brick Game Vert',
    imageUrl: '/antiquites/brick_game_green.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Jeux Électroniques Vintage',
    material: 'Plastique vert pomme, écran LCD à cristaux liquides',
    periodOrStyle: 'Années 1990',
    condition: 'Écran et touches en bel état cosmétique',
    dimensions: 'H : 18 cm × L : 8 cm × P : 2,5 cm',
    quantity: '1',
    price: '',
    notes: 'Console de poche culte des années 90 comprenant le jeu de briques.',
  },
  {
    id: 'art-antiq-16',
    ref: 'INV-2025/01-16',
    name: 'Dictaphone Sony à cassette',
    imageUrl: '/antiquites/dictaphone_sony.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Audio & Matériel de Reportage',
    material: 'Plastique',
    periodOrStyle: 'Années 1980',
    condition: 'Châssis noir avec dragonne et compartiment microcassette',
    dimensions: 'H : 13 cm × L : 6,5 cm × P : 2,8 cm',
    quantity: '1',
    price: '',
    notes: 'Enregistreur portable vocal Sony à microcassette avec micro intégré.',
  },

  // Page 9
  {
    id: 'art-antiq-17',
    ref: 'INV-2025/01-17',
    name: 'Appareil Photo Argentique Télémétrique Vintage Chromé',
    imageUrl: '/antiquites/camera_nikon_compact.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Photographie Ancienne',
    material: 'Boîtier métal chromé et gainage noir texturé',
    periodOrStyle: 'Années 1960 - 1970',
    condition: 'Optique claire, bel aspect de collection argentique',
    dimensions: 'L : 14 cm × H : 8,5 cm × P : 7 cm',
    quantity: '1',
    price: '',
    notes: 'Appareil photo télémétrique 35mm mécanique à mise au point manuelle.',
  },
  {
    id: 'art-antiq-18',
    ref: 'INV-2025/01-18',
    name: 'Appareil Photo Compact Argentique Nikon Noir',
    imageUrl: '/antiquites/camera_nikon_compact.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Photographie & Optique',
    material: 'Boîtier noir compact, objectif fixe Nikon haute définition',
    periodOrStyle: 'Années 1980 - 1990',
    condition: 'Complet avec son volet coulissant et dragonne',
    dimensions: 'L : 12,5 cm × H : 7 cm × P : 4,5 cm',
    quantity: '1',
    price: '',
    notes: 'Compact argentique autofocus 35mm Nikon de haute précision.',
  },

  // Page 10
  {
    id: 'art-antiq-19',
    ref: 'INV-2025/01-19',
    name: 'Manette Sony PSone',
    imageUrl: '/antiquites/psone_controller.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Jeux Vidéo & Rétrogaming',
    material: 'Plastique',
    periodOrStyle: 'Années 2000',
    condition: 'Manette originale Sony coloris gris clair pour console PSone',
    dimensions: 'L : 15 cm × P : 9,5 cm',
    quantity: '1',
    price: '',
    notes: 'Manette analogique officielle pour console Sony PlayStation One.',
  },
  {
    id: 'art-antiq-20',
    ref: 'INV-2025/01-20',
    name: 'Appareil Photo Argentique Compact Noir à Flash Rétractable',
    imageUrl: '/antiquites/camera_compact_flash.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Photographie & Optique',
    material: 'Boîtier plastique moulé noir, flash escamotable',
    periodOrStyle: 'Années 1990',
    condition: 'Bon état général de conservation',
    dimensions: 'L : 12 cm × H : 7 cm × P : 4 cm',
    quantity: '1',
    price: '',
    notes: 'Appareil photographique compact tout automatique à pellicule 35mm.',
  },

  // Page 11
  {
    id: 'art-antiq-21',
    ref: 'INV-2025/01-21',
    name: 'Jumelles / Appareil Rétro Bicolore Rouge & Blanc',
    imageUrl: '/antiquites/retro_viewer.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Optique & Curiosités',
    material: 'Plastique moulé rouge vif et ivoire, oculaires intégrés',
    periodOrStyle: 'Années 1970 - 1980',
    condition: 'Design rétro vintage bicolore emblématique',
    dimensions: 'L : 14 cm × P : 10 cm × H : 7 cm',
    quantity: '1',
    price: '',
    notes: 'Visionneuse ou jumelles stéréoscopiques au design pop rétro.',
  },
  {
    id: 'art-antiq-22',
    ref: 'INV-2025/01-22',
    name: 'Caméscope Vidéo Vintage à Poignée de Prise de Vue',
    imageUrl: '/antiquites/camcorder_video8.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Cinéma & Vidéo Vintage',
    material: 'Boîtier noir à poignée revolver, objectif zoom optique',
    periodOrStyle: 'Années 1980',
    condition: 'Poignée ergonomique et optique zoom préservées',
    dimensions: 'L : 28 cm × H : 22 cm × P : 12 cm',
    quantity: '1',
    price: '',
    notes: 'Caméscope analogique portable pour reportage vidéo vintage.',
  },

  // Page 12
  {
    id: 'art-antiq-23',
    ref: 'INV-2025/01-23',
    name: 'Lecteur Enregistreur Portable à Cassette Audio Noir',
    imageUrl: '/antiquites/cassette_player_portable.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Audio & Hi-Fi Vintage',
    material: 'Boîtier plastique noir avec câbles et écouteurs d\\\'époque',
    periodOrStyle: 'Années 1980 - 1990',
    condition: 'Touches mécaniques de lecture et d\\\'enregistrement complètes',
    dimensions: 'L : 16 cm × P : 12 cm × H : 4 cm',
    quantity: '1',
    price: '',
    notes: 'Magnétophone enregistreur de table compact avec prise micro et casque.',
  },
  {
    id: 'art-antiq-24',
    ref: 'INV-2025/01-24',
    name: 'Soulier Artisanal Sculpté Vintage en Cuir Multicolore',
    imageUrl: '/antiquites/leather_shoe_vintage.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Art Populaire & Artisanat de Cuir',
    material: 'Cuir naturel assemblé et teinté main, lanières polychromes',
    periodOrStyle: 'Milieu du XXe siècle',
    condition: 'Superbe patine artisanale cirée aux nuances vives',
    dimensions: 'L : 26 cm × H : 14 cm',
    quantity: '1',
    price: '',
    notes: 'Soulier décoratif traditionnel en cuir tressé et peint à la main.',
  },

  // Page 13
  {
    id: 'art-antiq-25',
    ref: 'INV-2025/01-25',
    name: 'Sony Walkman FM/AM',
    imageUrl: '/antiquites/walkman_sony.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Audio & Hi-Fi Vintage',
    material: 'Plastique',
    periodOrStyle: 'Années 1980-1990',
    condition: 'Compartiment cassette transparent, tuner FM/AM stéréo',
    dimensions: 'H : 12 cm × L : 9 cm × P : 3,5 cm',
    quantity: '1',
    price: '',
    notes: 'Le légendaire baladeur cassette portable Sony avec récepteur radio FM/AM.',
  },
  {
    id: 'art-antiq-26',
    ref: 'INV-2025/01-26',
    name: 'Téléphone Mural Ancien en Bois à Double Cloche en Laiton',
    imageUrl: '/antiquites/wall_phone_wood.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Ancienne & Objets d\\\'Atelier',
    material: 'Caisse en chêne / noyer massif, timbres de sonnerie en laiton poli',
    periodOrStyle: 'Début du XXe siècle (circa 1910 - 1920)',
    condition: 'Magnifique état patrimonial avec écouteur déporté et sonnettes',
    dimensions: 'H : 48 cm × L : 24 cm × P : 18 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone mural ancien de collection avec générateur à manivelle et combiné.',
  },

  // Page 14
  {
    id: 'art-antiq-27',
    ref: 'INV-2025/01-27',
    name: 'Téléviseur Portable Combiné Radio Rétro avec Poignée',
    imageUrl: '/antiquites/portable_tv_radio.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléviseurs & Rétro Électronique',
    material: 'Plastique et métal, écran miniature cathodique noir & blanc',
    periodOrStyle: 'Années 1980',
    condition: 'Poignée de transport et sélecteurs de bandes d\\\'origine',
    dimensions: 'L : 22 cm × P : 20 cm × H : 18 cm',
    quantity: '1',
    price: '',
    notes: 'Poste combiné TV noir & blanc portable avec récepteur radio AM/FM.',
  },
  {
    id: 'art-antiq-28',
    ref: 'INV-2025/01-28',
    name: 'Poste Radio-Cassette Boombox Portable Noir & Rouge',
    imageUrl: '/antiquites/boombox_black_red.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Audio & Hi-Fi Vintage',
    material: 'Plastique moulé noir et rouge, haut-parleurs stéréo intégrés',
    periodOrStyle: 'Années 1980 - 1990',
    condition: 'Format portable avec poignée escamotable et antenne',
    dimensions: 'L : 45 cm × H : 22 cm × P : 14 cm',
    quantity: '1',
    price: '',
    notes: 'Radiocassette stéréo vintage pour l\\\'écoute et l\\\'enregistrement nomade.',
  },

  // Page 15
  {
    id: 'art-antiq-29',
    ref: 'INV-2025/01-29',
    name: 'Caisse Enregistreuse / Terminal Électronique Rétro',
    imageUrl: '/antiquites/cash_register_retro.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Machines de Commerce & Vintage',
    material: 'Châssis robuste beige et ocre, écran opérateur inclinable',
    periodOrStyle: 'Années 1980',
    condition: 'Clavier de saisie et écran fluorescent fonctionnel',
    dimensions: 'L : 38 cm × P : 35 cm × H : 28 cm',
    quantity: '1',
    price: '',
    notes: 'Terminal de point de vente rétro pour commerces et boutiques d\\\'époque.',
  },
  {
    id: 'art-antiq-30',
    ref: 'INV-2025/01-30',
    name: 'Téléviseur Vintage Tube Cathodique Finition Bois',
    imageUrl: '/antiquites/crt_tv_wood.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléviseurs & Salons Anciens',
    material: 'Coffre en bois verni, écran cathodique bombé, molettes dorées',
    periodOrStyle: 'Années 1970',
    condition: 'Superbe esthétique vintage des années 70 avec touches rotatives',
    dimensions: 'L : 52 cm × P : 38 cm × H : 42 cm',
    quantity: '1',
    price: '',
    notes: 'Téléviseur couleur de salon vintage habillé d\\\'un meuble en bois d\\\'époque.',
  },

  // Page 16
  {
    id: 'art-antiq-31',
    ref: 'INV-2025/01-31',
    name: 'Grand Projecteur Cinéma Vintage sur Haut Trépied',
    imageUrl: '/antiquites/cinema_projector_tall.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Cinéma & Éclairage de Studio',
    material: 'Tête de projection métallique, trépied d\\\'atelier réglable',
    periodOrStyle: 'Milieu du XXe siècle',
    condition: 'Ensemble monumental d\\\'atelier de projection cinématographique',
    dimensions: 'Hauteur totale : 175 cm × Envergure trépied : 65 cm',
    quantity: '1',
    price: '',
    notes: 'Projecteur de film cinéma professionnel sur haut piétement tripode métallique.',
  },
  {
    id: 'art-antiq-32',
    ref: 'INV-2025/01-32',
    name: 'Téléviseur Moniteur Cathodique Argenté de Salon',
    imageUrl: '/antiquites/crt_monitor_silver.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléviseurs & Rétro',
    material: 'Boîtier gris argenté, tube cathodique couleur 4:3',
    periodOrStyle: 'Années 1990 - 2000',
    condition: 'Tube cathodique intact, panneau de commandes frontal complet',
    dimensions: 'Diagonale : 36 cm (14 pouces) • L : 38 cm × H : 35 cm',
    quantity: '1',
    price: '',
    notes: 'Téléviseur compact de salon ou de chambre au format cathodique traditionnel.',
  },

  // Page 17
  {
    id: 'art-antiq-33',
    ref: 'INV-2025/01-33',
    name: 'Téléviseur Cathodique Portable Noir Écran Bombé',
    imageUrl: '/antiquites/portable_tv_radio.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléviseurs & Rétro',
    material: 'Coque plastique noir mat, écran verre bombé',
    periodOrStyle: 'Années 1980',
    condition: 'Format compact de chambre ou voyage',
    dimensions: 'L : 32 cm × H : 30 cm × P : 30 cm',
    quantity: '1',
    price: '',
    notes: 'Moniteur TV vintage noir à tube cathodique bombé.',
  },
  {
    id: 'art-antiq-34',
    ref: 'INV-2025/01-34',
    name: 'Téléviseur Cathodique Rétro Noir Compact',
    imageUrl: '/antiquites/crt_monitor_silver.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléviseurs & Rétro',
    material: 'Plastique noir texturé, tube cathodique d\\\'époque',
    periodOrStyle: 'Années 1980 - 1990',
    condition: 'Bon état de présentation générale',
    dimensions: 'L : 30 cm × H : 28 cm × P : 28 cm',
    quantity: '1',
    price: '',
    notes: 'Poste de télévision d\\\'appoint rétro à écran cathodique.',
  },

  // Page 18
  {
    id: 'art-antiq-35',
    ref: 'INV-2025/01-35',
    name: 'Moniteur Vidéo Professionnel Cathodique Sony Trinitron',
    imageUrl: '/antiquites/sony_pvm_trinitron.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Audiovisuel Professionnel & Moniteurs',
    material: 'Châssis métallique noir de studio, tube Trinitron haute résolution',
    periodOrStyle: 'Années 1990 (Sony PVM / Broadcast)',
    condition: 'Panneau de commandes professionnelles latéral complet',
    dimensions: 'L : 36 cm × P : 38 cm × H : 34 cm',
    quantity: '1',
    price: '',
    notes: 'Moniteur vidéo de référence Sony Trinitron plébiscité en régie et rétrogaming.',
  },
  {
    id: 'art-antiq-36',
    ref: 'INV-2025/01-36',
    name: 'Moniteur Informatique Terminal Cathodique Vintage Beige',
    imageUrl: '/antiquites/terminal_crt_beige.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Informatique Ancienne & Terminaux',
    material: 'Plastique beige d\\\'époque, écran cathodique monochrome',
    periodOrStyle: 'Années 1980',
    condition: 'Pied inclinable et tube cathodique d\\\'origine',
    dimensions: 'L : 34 cm × P : 32 cm × H : 33 cm',
    quantity: '1',
    price: '',
    notes: 'Écran d\\\'ordinateur ou terminal de télécommunication vintage des années 80.',
  },

  // Page 19
  {
    id: 'art-antiq-37',
    ref: 'INV-2025/01-37',
    name: 'Guitare Électrique Type Stratocaster Rouge Vif & Blanc',
    imageUrl: '/antiquites/stratocaster_red.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Instruments de Musique & Guitares',
    material: 'Corps en bois verni rouge fiesta, manche en érable, plaque blanche',
    periodOrStyle: 'Style Stratocaster, fin XXe siècle',
    condition: 'Micros simples, accastillage et potentiomètres complets',
    dimensions: 'Longueur totale : 100 cm • Diapason 648 mm',
    quantity: '1',
    price: '',
    notes: 'Guitare électrique six cordes à double pan coupé avec sélecteur 5 positions.',
  },
  {
    id: 'art-antiq-38',
    ref: 'INV-2025/01-38',
    name: 'Poste Radio-Cassette Stéréo Sony Boombox Noir',
    imageUrl: '/antiquites/boombox_black_red.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Audio & Hi-Fi Vintage',
    material: 'Châssis noir profilé avec double enceinte stéréo et lecteur cassette',
    periodOrStyle: 'Années 1990 (Sony)',
    condition: 'Grilles d\\\'enceintes métalliques préservées avec poignée intégrée',
    dimensions: 'L : 48 cm × H : 20 cm × P : 16 cm',
    quantity: '1',
    price: '',
    notes: 'Radio-cassette portable stéréo Sony Mega Bass avec tuner digital.',
  },

  // Page 20
  {
    id: 'art-antiq-39',
    ref: 'INV-2025/01-39',
    name: 'Téléphone Portable Vintage à Clapet & Antenne Type StarTAC',
    imageUrl: '/antiquites/motorola_startac.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique noir, clapet rabattable et antenne télescopique',
    periodOrStyle: 'Années 1990 (Motorola)',
    condition: 'Modèle culte des débuts du téléphone mobile personnel',
    dimensions: 'Fermé : 9,5 cm × 5,5 cm × 3 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone cellulaire emblématique à clapet pliant avec antenne extensible.',
  },
  {
    id: 'art-antiq-40',
    ref: 'INV-2025/01-40',
    name: 'Télévision portable',
    imageUrl: '/antiquites/portable_tv_yellow.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléviseurs & Rétro',
    material: 'Plastique',
    periodOrStyle: 'Années 1970',
    condition: 'Coloris pop jaune crème des années 70, poignée intégrée',
    dimensions: 'L : 26 cm × H : 22 cm × P : 24 cm',
    quantity: '1',
    price: '',
    notes: 'Téléviseur rétro portable design Space Age aux formes arrondies.',
  },

  // Page 21
  {
    id: 'art-antiq-41',
    ref: 'INV-2025/01-41',
    name: 'Téléphone portable à clapet Samsung',
    imageUrl: '/antiquites/samsung_flip_silver.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique et métal',
    periodOrStyle: 'Années 2000',
    condition: 'Finition gris argenté métallisé, clapet fluide',
    dimensions: 'Fermé : 8,5 cm × 4,5 cm × 2,2 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone mobile compact à clapet avec double écran.',
  },
  {
    id: 'art-antiq-42',
    ref: 'INV-2025/01-42',
    name: 'Téléphone portable Nokia 3310',
    imageUrl: '/antiquites/nokia_3310.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique',
    periodOrStyle: 'Années 2000',
    condition: 'Téléphone culte indestructible, coque bleu nuit d\\\'origine',
    dimensions: 'H : 11,3 cm × L : 4,8 cm × P : 2,2 cm',
    quantity: '1',
    price: '',
    notes: 'Le mythique Nokia 3310, modèle le plus vendu et résistant de l\\\'histoire mobile.',
  },

  // Page 22
  {
    id: 'art-antiq-43',
    ref: 'INV-2025/01-43',
    name: 'Téléphone mobile Samsung QWERTY rouge',
    imageUrl: '/antiquites/samsung_qwerty_red.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique et métal',
    periodOrStyle: 'Années 2000',
    condition: 'Clavier complet QWERTY physique pour messagerie',
    dimensions: 'H : 10 cm × L : 5,8 cm × P : 1,4 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone messagerie Samsung coloris rouge carmin avec clavier intégral.',
  },
  {
    id: 'art-antiq-44',
    ref: 'INV-2025/01-44',
    name: 'Téléphone portable à clapet Sharp',
    imageUrl: '/antiquites/samsung_flip_silver.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique et métal',
    periodOrStyle: 'Années 2000',
    condition: 'Écran couleur et charnière à clapet robuste',
    dimensions: 'Fermé : 9 cm × 4,8 cm × 2,4 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone à clapet Sharp doté d\\\'un appareil photo numérique intégré.',
  },

  // Page 23
  {
    id: 'art-antiq-45',
    ref: 'INV-2025/01-45',
    name: 'Téléphone portable Nokia',
    imageUrl: '/antiquites/nokia_3310.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique',
    periodOrStyle: 'Années 2000',
    condition: 'Design épuré scandinave Nokia finition argentée',
    dimensions: 'H : 10,5 cm × L : 4,5 cm × P : 1,8 cm',
    quantity: '1',
    price: '',
    notes: 'Mobile monobloc Nokia compact avec écran rétroéclairé.',
  },
  {
    id: 'art-antiq-46',
    ref: 'INV-2025/01-46',
    name: 'Téléphone portable Motorola à clapet',
    imageUrl: '/antiquites/motorola_startac.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique',
    periodOrStyle: 'Années 2000',
    condition: 'Clapet ultra fin emblématique Motorola',
    dimensions: 'Fermé : 9,8 cm × 5,2 cm × 1,5 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone clapet fin et racé Motorola de la génération Razr / V3.',
  },

  // Page 24
  {
    id: 'art-antiq-47',
    ref: 'INV-2025/01-47',
    name: 'Ancien téléphone portable Samsung',
    imageUrl: '/antiquites/samsung_flip_silver.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique et métal',
    periodOrStyle: 'Années 2000',
    condition: 'Design compact à clapet avec antenne stub',
    dimensions: 'Fermé : 8,8 cm × 4,6 cm × 2,3 cm',
    quantity: '1',
    price: '',
    notes: 'Modèle à clapet Samsung des débuts des années 2000.',
  },
  {
    id: 'art-antiq-48',
    ref: 'INV-2025/01-48',
    name: 'Téléphone portable Ericsson GA628',
    imageUrl: '/antiquites/ericsson_ga628.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique',
    periodOrStyle: 'Années 1990',
    condition: 'Antenne courte fixe et façade interchangeable d\\\'origine',
    dimensions: 'H : 13 cm (sans antenne) × L : 4,8 cm × P : 2,5 cm',
    quantity: '1',
    price: '',
    notes: 'Modèle culte Ericsson GA628 des années 90 avec écran LCD une ligne.',
  },

  // Page 25
  {
    id: 'art-antiq-49',
    ref: 'INV-2025/01-49',
    name: 'Talkie walkie Motorola Talkabout',
    imageUrl: '/antiquites/talkabout_black.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Radiocommunication & Émetteurs',
    material: 'Plastique',
    periodOrStyle: 'Années 1990',
    condition: 'Boîtier antichoc noir mat, antenne souple et bouton PTT',
    dimensions: 'H : 16 cm avec antenne × L : 6 cm × P : 3,2 cm',
    quantity: '1',
    price: '',
    notes: 'Émetteur-récepteur radio UHF / PMR portable Motorola professionnel.',
  },
  {
    id: 'art-antiq-50',
    ref: 'INV-2025/01-50',
    name: 'Talkie walkie Motorola Talkabout',
    imageUrl: '/antiquites/talkabout_blue.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Radiocommunication & Émetteurs',
    material: 'Plastique',
    periodOrStyle: 'Années 1990',
    condition: 'Boîtier bleu avec écran rond rétroéclairé et bouton PTT latéral',
    dimensions: 'H : 16 cm avec antenne × L : 6 cm × P : 3,2 cm',
    quantity: '1',
    price: '',
    notes: 'Talkie-walkie Motorola Talkabout longue portée en coloris bleu de sécurité.',
  },

  // Page 26
  {
    id: 'art-antiq-51',
    ref: 'INV-2025/01-51',
    name: 'Talkie-Walkie / Téléphone Rétro Compact Noir à Antenne',
    imageUrl: '/antiquites/talkabout_black.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Radiocommunication Vintage',
    material: 'Plastique dur noir mat, écran digital rétroéclairé',
    periodOrStyle: 'Années 1990',
    condition: 'Format compact professionnel avec clip ceinture',
    dimensions: 'H : 14 cm × L : 5,5 cm × P : 3 cm',
    quantity: '1',
    price: '',
    notes: 'Terminal de communication radio portable robuste.',
  },
  {
    id: 'art-antiq-52',
    ref: 'INV-2025/01-52',
    name: 'Téléphone Portable Monobloc Rétro Noir',
    imageUrl: '/antiquites/ericsson_ga628.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique noir texturé, clavier numérique complet',
    periodOrStyle: 'Années 1990 - 2000',
    condition: 'Bon état de conservation de collection',
    dimensions: 'H : 12 cm × L : 4,5 cm × P : 2 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone portable vintage monobloc à touches en caoutchouc souple.',
  },

  // Page 27
  {
    id: 'art-antiq-53',
    ref: 'INV-2025/01-53',
    name: 'Téléphone Portable Compact Vintage Noir',
    imageUrl: '/antiquites/alcatel_hc800.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Boîtier plastique avec antenne droite rigide',
    periodOrStyle: 'Années 1990',
    condition: 'Modèle compact robuste de première génération GSM',
    dimensions: 'H : 13 cm × L : 4,6 cm × P : 2,5 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone mobile vintage robuste à antenne fixe.',
  },
  {
    id: 'art-antiq-54',
    ref: 'INV-2025/01-54',
    name: 'Téléphone portable Alcatel HC800',
    imageUrl: '/antiquites/alcatel_hc800.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Plastique',
    periodOrStyle: 'Années 1990',
    condition: 'Modèle historique de la gamme nomade Alcatel',
    dimensions: 'H : 14 cm × L : 5 cm × P : 2,8 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone portable Alcatel One Touch HC800 des débuts des réseaux mobiles.',
  },

  // Page 28
  {
    id: 'art-antiq-55',
    ref: 'INV-2025/01-55',
    name: 'Téléphone Mobile Vintage à Clapet Noir avec Antenne',
    imageUrl: '/antiquites/motorola_startac.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Mobile Vintage',
    material: 'Coque plastique noir, clapet protecteur',
    periodOrStyle: 'Années 1990 - 2000',
    condition: 'Mécanique d\\\'ouverture fluide et antenne intacte',
    dimensions: 'Fermé : 9 cm × 5 cm × 2,8 cm',
    quantity: '1',
    price: '',
    notes: 'Mobile vintage rabattable protégeant le clavier lors des déplacements.',
  },
  {
    id: 'art-antiq-56',
    ref: 'INV-2025/01-56',
    name: 'Téléphone Vintage à Cadran Rotatif Orange PTT',
    imageUrl: '/antiquites/phone_ptt_orange.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Fixe Vintage',
    material: 'Plastique teinté orange vif, cadran rotatif transparent PTT',
    periodOrStyle: 'Années 1970 - 1980 (Modèle S63 Orange)',
    condition: 'Pièce iconique du design vintage français des années 70',
    dimensions: 'L : 22 cm × P : 20 cm × H : 14 cm',
    quantity: '1',
    price: '',
    notes: 'Le légendaire poste téléphonique S63 orange PTT à cadran rotatif des années 70.',
  },

  // Page 29
  {
    id: 'art-antiq-57',
    ref: 'INV-2025/01-57',
    name: 'Téléphone Ancien en Bakélite Noire à Cadran Rotatif',
    imageUrl: '/antiquites/phone_bakelite_black.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Fixe Ancienne',
    material: 'Bakélite noire moulée brillante, cadran chromé',
    periodOrStyle: 'Années 1930 - 1950 (Type PTT 24 / U43)',
    condition: 'Lourd combiné en bakélite, cloche interne métallique d\\\'origine',
    dimensions: 'L : 24 cm × P : 19 cm × H : 16 cm',
    quantity: '2',
    price: '',
    notes: 'Paire de postes téléphoniques d\\\'époque en véritable bakélite noire à cadran à trous.',
  },
  {
    id: 'art-antiq-58',
    ref: 'INV-2025/01-58',
    name: 'Téléphone Vintage à Cadran Rotatif Blanc Ivoire S63',
    imageUrl: '/antiquites/phone_s63_ivory.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Fixe Vintage',
    material: 'Plastique thermoformé blanc ivoire, cadran rotatif transparent',
    periodOrStyle: 'Années 1970 (S63 PTT)',
    condition: 'Belle teinte ivoire préservée avec son combiné d\\\'origine',
    dimensions: 'L : 22 cm × P : 20 cm × H : 14 cm',
    quantity: '1',
    price: '',
    notes: 'Poste téléphonique S63 vintage couleur blanc ivoire.',
  },

  // Page 30
  {
    id: 'art-antiq-59',
    ref: 'INV-2025/01-59',
    name: 'Téléphone Rétro à Cadran Rotatif Gris Cendré S63',
    imageUrl: '/antiquites/phone_s63_grey.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Fixe Vintage',
    material: 'Plastique gris clair PTT, combiné ergonomique',
    periodOrStyle: 'Années 1970 - 1980',
    condition: 'Cadran rotatif avec retour mécanique fluide',
    dimensions: 'L : 22 cm × P : 20 cm × H : 14 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone de bureau officiel PTT S63 en livrée grise.',
  },
  {
    id: 'art-antiq-60',
    ref: 'INV-2025/01-60',
    name: 'Téléphone Vintage à Touches Marron Ocre',
    imageUrl: '/antiquites/phone_keys_brown.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Fixe Vintage',
    material: 'Plastique deux tons marron et beige, clavier à touches numériques',
    periodOrStyle: 'Années 1980',
    condition: 'Touches souples et cordon torsadé d\\\'origine',
    dimensions: 'L : 22 cm × P : 18 cm × H : 12 cm',
    quantity: '1',
    price: '',
    notes: 'Poste fixe à touches des années 80 avec rappel de numéro et tonalité.',
  },

  // Page 31
  {
    id: 'art-antiq-61',
    ref: 'INV-2025/01-61',
    name: 'Cabine / Téléphone Public Mural à Monnayeur Rouge',
    imageUrl: '/antiquites/payphone_red.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Publique & Objets Urbains',
    material: 'Tôle métallique laquée rouge vermillon, fente à pièces et combiné blindé',
    periodOrStyle: 'Années 1970 - 1980',
    condition: 'Remarquable pièce de collection urbaine avec coffre de monnaie',
    dimensions: 'H : 55 cm × L : 28 cm × P : 22 cm',
    quantity: '1',
    price: '',
    notes: 'Taxiphone / cabine publique murale à jetons ou pièces de monnaie.',
  },
  {
    id: 'art-antiq-62',
    ref: 'INV-2025/01-62',
    name: 'Téléphone Rétro à Cadran Rotatif Beige Clair',
    imageUrl: '/antiquites/phone_s63_ivory.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Téléphonie Fixe Vintage',
    material: 'Plastique couleur sable, cadran rotatif',
    periodOrStyle: 'Années 1970',
    condition: 'Bon état de conservation d\\\'origine',
    dimensions: 'L : 22 cm × P : 20 cm × H : 14 cm',
    quantity: '1',
    price: '',
    notes: 'Téléphone fixe vintage S63 à cadran rotatif couleur sable chaud.',
  },

  // Page 32
  {
    id: 'art-antiq-63',
    ref: 'INV-2025/01-63',
    name: 'Jerrican d\\\'Essence Militaire en Métal Vert Kaki',
    imageUrl: '/antiquites/jerrycan_military_green.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Militaria & Objets Métalliques',
    material: 'Acier embouti peint vert olive / kaki, poignée triple et bouchon à clapet',
    periodOrStyle: 'Milieu du XXe siècle (Contenance 20 Litres)',
    condition: 'Authentique patine de terrain sans perforation, fermeture étanche',
    dimensions: 'H : 47 cm × L : 35 cm × P : 16,5 cm',
    quantity: '1',
    price: '',
    notes: 'Véritable jerrycan métallique militaire 20L avec nervures de renfort en croix.',
  },
  {
    id: 'art-antiq-64',
    ref: 'INV-2025/01-64',
    name: 'Mégaphone / Porte-Voix Portable Blanc & Bleu',
    imageUrl: '/antiquites/megaphone_white_blue.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Sonorisation & Appareils Vintage',
    material: 'Corps conique en métal et plastique, poignée pistolet avec gâchette',
    periodOrStyle: 'Années 1970 - 1980',
    condition: 'Pavillon intact avec sangle de portage',
    dimensions: 'Longueur : 36 cm • Diamètre pavillon : 22 cm',
    quantity: '1',
    price: '',
    notes: 'Porte-voix amplifié à poignée pistolet pour manifestations et rassemblements.',
  },

  // Page 33
  {
    id: 'art-antiq-65',
    ref: 'INV-2025/01-65',
    name: 'Valise Vintage Rigide de Voyage Beige Crème',
    imageUrl: '/antiquites/suitcase_vintage_beige.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Bagagerie & Voyage Vintage',
    material: 'Fibre vulcanisée rigide beige crème, renforts d\\\'angle, serrures en laiton',
    periodOrStyle: 'Années 1960',
    condition: 'Fermoirs métalliques et poignée solide d\\\'origine',
    dimensions: 'L : 65 cm × P : 42 cm × H : 20 cm',
    quantity: '1',
    price: '',
    notes: 'Grande valise rigide de voyage vintage aux finitions sellier.',
  },
  {
    id: 'art-antiq-66',
    ref: 'INV-2025/01-66',
    name: 'Malle / Valise Vintage Rétro Grise Granitée',
    imageUrl: '/antiquites/suitcase_vintage_grey.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Bagagerie & Voyage Vintage',
    material: 'Revêtement texturé gris ardoise, charnières et fermetures en métal',
    periodOrStyle: 'Années 1960 - 1970',
    condition: 'Belle structure robuste avec poignée centrale',
    dimensions: 'L : 60 cm × P : 40 cm × H : 18 cm',
    quantity: '1',
    price: '',
    notes: 'Valise rétro de malle-poste robuste à texture granitée.',
  },

  // Page 34
  {
    id: 'art-antiq-67',
    ref: 'INV-2025/01-67',
    name: 'Trompe / Pavillon Acoustique Diffuseur Blanc Vintage',
    imageUrl: '/antiquites/acoustic_horn_white.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Sonorisation Ancienne & Rétro',
    material: 'Pavillon évasé en aluminium laqué blanc, étrier de fixation métallique',
    periodOrStyle: 'Années 1960 - 1970',
    condition: 'Superbe pavillon acoustique de diffusion d\\\'atelier',
    dimensions: 'Longueur : 42 cm • Diamètre pavillon : 32 cm',
    quantity: '1',
    price: '',
    notes: 'Pavillon diffuseur sonore en métal pour sonorisation publique ou d\\\'usine.',
  },
  {
    id: 'art-antiq-68',
    ref: 'INV-2025/01-68',
    name: 'Malle / Valise Ancienne en Cuir Fauve Camel à Renforts',
    imageUrl: '/antiquites/leather_trunk_camel.svg',
    imageFit: 'contain',
    folder: 'Antiquités',
    category: 'Bagagerie & Cuir Ancien',
    material: 'Cuir épais patiné fauve camel, sangles de serrage, cornières métalliques',
    periodOrStyle: 'Début du XXe siècle',
    condition: 'Magnifique patine du cuir vieilli, coutures et fermoirs solides',
    dimensions: 'L : 70 cm × P : 45 cm × H : 22 cm',
    quantity: '1',
    price: '',
    notes: 'Superbe malle de voyage en cuir pleine fleur camel patiné par les voyages.',
  },
];
`;

const destFile = '/app/applet/src/data/defaultCatalog.ts';
fs.writeFileSync(destFile, catalogCode);
console.log('Successfully wrote 68 real depot articles to ' + destFile);
